import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/ui/Navbar";
import { Footer } from "@/components/ui/Footer";
import { FloatingWhatsAppButton } from "@/components/ui/FloatingWhatsAppButton";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://silverdogtraining.com'),
  title: "Silver Dog Training - Educamos Guías, Adiestramos Perros, Creamos Recuerdos",
  description: "Entrenamiento profesional de perros con el método NePoPo®. Especialistas en adiestramiento canino, detección K9 y protección. 8+ años de experiencia fortaleciendo vínculos entre guías y perros.",
  keywords: ["adiestramiento canino", "entrenamiento perros", "NePoPo", "K9", "detección canina", "protección canina", "Silver Dog Training"],
  authors: [{ name: "Yonathan Pérez" }],
  creator: "Silver Dog Training",
  publisher: "Silver Dog Training",
  robots: "index, follow",
  openGraph: {
    type: "website",
    locale: "es_ES",
    url: "https://silverdogtraining.com",
    siteName: "Silver Dog Training",
    title: "Silver Dog Training - Educamos Guías, Adiestramos Perros, Creamos Recuerdos",
    description: "Entrenamiento profesional de perros con el método NePoPo®. Especialistas en adiestramiento canino, detección K9 y protección.",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Silver Dog Training - Adiestramiento Profesional Canino",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Silver Dog Training - Educamos Guías, Adiestramos Perros, Creamos Recuerdos",
    description: "Entrenamiento profesional de perros con el método NePoPo®. Especialistas en adiestramiento canino, detección K9 y protección.",
    images: ["/og-image.jpg"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={inter.variable} data-scroll-behavior="smooth">
      <head>

        {/* Mobile-first viewport and optimization */}
        <meta name="HandheldFriendly" content="true" />
        <meta name="MobileOptimized" content="320" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="FixTeam" />

        {/* Touch icons for mobile devices */}
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="192x192" href="/icon-192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/icon-512.png" />

        {/* Manifest for PWA capabilities - Auto-generated by Next.js from manifest.ts */}

        {/* Theme color for mobile browsers */}
        <meta name="theme-color" content="#cb6622" />
        <meta name="msapplication-TileColor" content="#cb6622" />
        <meta name="msapplication-config" content="/browserconfig.xml" />

        {/* Performance and security headers */}
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="referrer" content="strict-origin-when-cross-origin" />

      </head>
      <body className="font-sans antialiased min-h-screen flex flex-col">
      <Navbar showSocialIcons={true} />

        <main className="flex-1">
          {children}
        </main>
        <Footer />
        
        {/* Floating WhatsApp Button */}
        <FloatingWhatsAppButton />
      </body>
    </html>
  );
}
